on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC16F877A
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC16F877A
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/f886e3b623409ea56a2d3bdcfbf20e98
          gist_title: Pr치ctica 18 - Bluetooth HC-05 PIC16F877A CCS.c
          gist_description: Pr치cticas PIC CCS
          github_file: Proyecto/PIC16F877A/HC05.c
          file_encoding: WINDOWS-1252
    #PIC16F887
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC16F887
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/d1679487e57bbcb3036a985baa701fb5
          gist_title: Pr치ctica 18 - Bluetooth HC-05 PIC16F887 CCS.c
          gist_description: Pr치cticas PIC CCS
          github_file: Proyecto/PIC16F887/HC05.c
          file_encoding: WINDOWS-1252